apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 58.3.1
      helm:
        valueFiles:
          - $values/monitoring/helm-values/kube-prometheus-stack-values.yaml

    - repoURL: https://github.com/vinayak228/ofti-bootcamp
      targetRevision: develop
      ref: values
